<?xml version="1.0" encoding="utf-8"?><Database Name="INCOMETAX" Class="DataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MY_PC;Initial Catalog=INCOMETAX;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="INCOMETAXConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FILE_DETAILS" Member="FILE_DETAILs">
    <Type Name="FILE_DETAIL">
      <Column Name="FILE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FILE_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ASSIGN_STAFF_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ASSIGN_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IS_ASSIGN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="COMPLETE_IN_DAYS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DEADLINE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IS_PENDING" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IS_COMPLETED" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IS_DELETE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[USER]" Member="USERs">
    <Type Name="USER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RollId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>